name: Build SRPMs

on:
  push:
    paths:
      - common/**
      - .github/workflows/build.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  build-rpms:
    strategy:
      matrix:
        repository:
          - common
        build:
          - distro: fedora
            version: 44
            arch: x86_64
            runner: ubuntu-latest
          - distro: fedora
            version: 44
            arch: aarch64
            runner: ubuntu-24.04-arm
          - distro: fedora
            version: 45
            arch: x86_64
            runner: ubuntu-latest
          - distro: fedora
            version: 45
            arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.build.runner }}
    container: 
      image: ghcr.io/teamsbc/ci-packages:${{ matrix.build.distro }}-${{ matrix.build.version }}
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v6
      - name: "Setup"
        env:
          LATEST: /repo/${{ github.ref_name }}/latest/${{ matrix.build.version }}/${{ matrix.build.arch }}/${{ matrix.repository }}
        run: |
          echo "%_topdir %(pwd)" >> ~/.rpmmacros
          mkdir /rpms/
          mkdir /repo/
          DATED=/repo/${{ github.ref_name }}/$(date +%Y.%m.%d)/${{ matrix.build.version }}/${{ matrix.build.arch }}/${{ matrix.repository }}
          mkdir -p $LATEST
          mkdir -p $DATED
          echo "LATEST=$LATEST" >> $GITHUB_ENV
          echo "DATED=$DATED" >> $GITHUB_ENV
      - name: "Build Requirements"
        run: |
          BUILDREQS=""
          for DIR in ./${{ matrix.repository }}/*/; do
            pushd $DIR
            BUILDREQS_ADD=$(rpmspec -q --srpm --buildrequires *.spec | xargs)
            BUILDREQS="${BUILDREQS_ADD} ${BUILDREQS}"
            popd
          done
          dnf install -y $BUILDREQS
      - name: "Build"
        run: |
          for DIR in ./${{ matrix.repository }}/*/; do
            pushd $DIR
            mkdir -p {BUILD,BUILDROOT,RPMS,SRPMS,SPECS,SOURCES}
            find . -maxdepth 1 -type f -exec cp -v {} SOURCES/ \;
            cp -v *.spec SPECS
            rpmbuild -ba *.spec
            popd
          done
      - name: "Import GPG Key"
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "${GPG_PRIVATE_KEY}" | gpg --batch --import
          echo "%_gpg_name signing@teamsbc.org" >> ~/.rpmmacros
      - name: "Sign"
        run: |
          find ./${{ matrix.repository }} -name '*.rpm' -exec rpmsign --addsign {} +
      - name: "Copy"
        run: |
          find ./${{ matrix.repository }} -name '*.rpm' -exec mv -t $LATEST {} +
      - name: "Repository"
        run: |
          cd $LATEST/
          createrepo_c .
      - name: "Copy to dated directory"
        run: |
          sudo cp -vra $LATEST/* $DATED/
      - name: "Upload"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT }}
        run: |
          aws s3 cp --recursive /repo \
            "s3://teamsbc-packages/" \
            --no-progress
          aws s3 cp common/teamsbc-repos/RPM-GPG-KEY-teamsbc \
            "s3://teamsbc-packages/RPM-GPG-KEY-teamsbc" \
            --no-progress
